stages:
  preprocess:
    cmd: uv run scripts/preprocess.py
    deps:
      - data/raw/customers.csv
      - scripts/preprocess.py
    outs:
      - data/processed/customers_cleaned.csv
  train:
    cmd: uv run scripts/train.py
    deps:
      - data/processed/customers_cleaned.csv
      - scripts/train.py
      - params.yaml
    params:
      - model
      - data
      - mlflow
    outs:
      - models/random_forest.pkl
  evaluate:
    cmd: uv run python scripts/evaluate.py
    deps:
      - data/processed/customers_cleaned.csv
      - models/random_forest.pkl
      - scripts/evaluate.py
      - metrics/mlflow_run_id.txt
    metrics:
      - metrics/eval_metrics.json:
          cache: false
